name: Production Release Pipeline

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Версия релиза'
        required: true
        type: string
jobs:
  # check-docker-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Log in to Yandex Container Registry
  #       run: echo "${{ secrets.CRY_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
  #     - name: Check Docker Image in Yandex Container Registry
  #       run: |
  #         IMAGE_NAME="cr.yandex/${{ secrets.CRY_ID }}/app:${{ github.event.inputs.release_version }}_latest"

  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker Image to VM
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME="cr.yandex/${{ secrets.CRY_ID }}/app:${{ github.event.inputs.release_version }}_latest"
            docker pull $IMAGE_NAME
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 3000:3000 $IMAGE_NAME
          
